name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Lucas Paula
    - APELLIDO=Perez
    - DOCUMENTO=76480263
    - NACIMIENTO=1925-10-27
    - NUMERO=5238
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config:/config
    - ./protocol:/protocol
  client2:
    container_name: client2
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - CLI_ID=2
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Gonzalo Lionel
    - APELLIDO=Perez
    - DOCUMENTO=55481103
    - NACIMIENTO=2014-12-27
    - NUMERO=6059
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config:/config
    - ./protocol:/protocol
  client3:
    container_name: client3
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - CLI_ID=3
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Lucas Carla
    - APELLIDO=Perez
    - DOCUMENTO=55413214
    - NACIMIENTO=1919-12-15
    - NUMERO=8908
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config:/config
    - ./protocol:/protocol
  client4:
    container_name: client4
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - CLI_ID=4
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Lucas Manolo
    - APELLIDO=Perez
    - DOCUMENTO=69487158
    - NACIMIENTO=2000-11-16
    - NUMERO=3310
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config:/config
    - ./protocol:/protocol
  client5:
    container_name: client5
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - CLI_ID=5
    - CLI_LOG_LEVEL=DEBUG
    - NOMBRE=Gonzalo Manolo
    - APELLIDO=Martinez
    - DOCUMENTO=62444117
    - NACIMIENTO=1939-10-10
    - NUMERO=3389
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config:/config
    - ./protocol:/protocol
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./protocol:/protocol
version: '3.9'
