name: tp0
networks:
  testing_net:
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client1:
    container_name: client1
    depends_on:
    - server
    entrypoint: python3 /main.py
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    - CHUNK_SIZE=1000
    image: client:latest
    networks:
    - testing_net
    volumes:
    - ./client/config:/config
    - ./protocol:/protocol
    - ./.data/dataset:/data
  server:
    container_name: server
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    image: server:latest
    networks:
    - testing_net
    volumes:
    - ./protocol:/protocol
version: '3.9'
